"""relacionamentoumparaum

Revision ID: 2409f7f18ae6
Revises: 1500a96b7db6
Create Date: 2024-06-05 20:51:27.513610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2409f7f18ae6'
down_revision = '1500a96b7db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('hash_log',
               existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32),
               type_=mysql.NCHAR(national=True, length=32),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('hash_log',
               existing_type=mysql.NCHAR(national=True, length=32),
               type_=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
