"""aumentando o tamanho do nome

Revision ID: 611ec4b24bfa
Revises: a9b4496cb5e8
Create Date: 2024-06-14 20:37:48.823197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '611ec4b24bfa'
down_revision = 'a9b4496cb5e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('hash_log',
               existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=50),
               type_=mysql.NCHAR(national=True, length=50),
               existing_nullable=True)

    with op.batch_alter_table('plano_de_saude', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=55),
               existing_nullable=True)

    with op.batch_alter_table('prontuario_paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prontuario_paciente', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('nome')

    with op.batch_alter_table('plano_de_saude', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=55),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('hash_log',
               existing_type=mysql.NCHAR(national=True, length=50),
               type_=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
