"""Adicionar relações entre Consulta, ProntuarioPaciente e PlanoDeSaude

Revision ID: a9b4496cb5e8
Revises: a732852604d0
Create Date: 2024-06-14 20:17:10.306238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9b4496cb5e8'
down_revision = 'a732852604d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_prontuario_paciente', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fk_plano_de_saude_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'prontuario_paciente', ['fk_prontuario_paciente'], ['id'])
        batch_op.create_foreign_key(None, 'plano_de_saude', ['fk_plano_de_saude_id'], ['id'])

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('hash_log',
               existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=50),
               type_=mysql.NCHAR(national=True, length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('hash_log',
               existing_type=mysql.NCHAR(national=True, length=50),
               type_=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=50),
               existing_nullable=True)

    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_plano_de_saude_id')
        batch_op.drop_column('fk_prontuario_paciente')

    # ### end Alembic commands ###
