"""bancodedados

Revision ID: fd1229badacc
Revises: 
Create Date: 2024-06-16 21:21:23.583624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd1229badacc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hora', sa.DateTime(), nullable=True),
    sa.Column('hash_log', mysql.NCHAR(national=True, length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plano_de_saude',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=55), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prontuario_paciente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('historico', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('whatsapp', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recepcionista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('telefone', sa.String(length=12), nullable=False),
    sa.Column('cpf', sa.String(length=12), nullable=False),
    sa.Column('crm', sa.String(length=60), nullable=False),
    sa.Column('fk_especialidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_especialidade_id'], ['especialidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('crm')
    )
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=True),
    sa.Column('fk_recepcionista_id', sa.Integer(), nullable=True),
    sa.Column('fk_medico_id', sa.Integer(), nullable=True),
    sa.Column('fk_prontuario_paciente', sa.Integer(), nullable=True),
    sa.Column('fk_plano_de_saude_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_medico_id'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['fk_plano_de_saude_id'], ['plano_de_saude.id'], ),
    sa.ForeignKeyConstraint(['fk_prontuario_paciente'], ['prontuario_paciente.id'], ),
    sa.ForeignKeyConstraint(['fk_recepcionista_id'], ['recepcionista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consulta')
    op.drop_table('medico')
    op.drop_table('recepcionista')
    op.drop_table('prontuario_paciente')
    op.drop_table('plano_de_saude')
    op.drop_table('log')
    op.drop_table('especialidade')
    # ### end Alembic commands ###
